version: 2.1

jobs:
  test-and-build:
    docker:
      - image: circleci/node:14 # Choose an appropriate Node.js version
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build React App
          command: |
            if [ $? -eq 0 ]; then
              npm run build
            else
              echo "Tests failed, skipping build."
            fi

workflows:
  version: 2
  test-and-build-workflow:
    jobs:
      - test-and-build
