version: 2.1

jobs: 
  test-build-and-deploy:
    docker:
      - image: circleci/node:14 # Choose an appropriate Node.js version
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build React App
          command: |
            if [ $? -eq 0 ]; then
              npm run build
            else
              echo "Tests failed, skipping build."
              exit 1
            fi
      - run:
          name: Deploy to EC2
          command: |
            chmod 400 /home/circleci/project/.circleci/react-app-key-pair.pem
            ssh -i $EC2_PRIVATE_KEY $EC2_USERNAME@$EC2_PUBLIC_IP "rm -rf /home/ec2-user/*"
            scp -i $EC2_PRIVATE_KEY -r build/* $EC2_USERNAME@$EC2_PUBLIC_IP:/home/ec2-user/
            ssh -i $EC2_PRIVATE_KEY $EC2_USERNAME@$EC2_PUBLIC_IP "bash /home/ec2-user/deploy-script.sh"

workflows:
  version: 2
  test-build-and-deploy-workflow:
    jobs:
      - test-build-and-deploy

